- name: Install driver
  hosts: all
  gather_facts: False
  # gather_subset: min
  # become: yes
  
  
  vars:
    version: 0.1.0
    wheel_filename: >-
      epi_ue_build_driver-{{ version }}-py3-none-any.whl
    local_src_path: >-
      {{ CTL_REPO_ROOT }}/dist/{{ wheel_filename }}
    remote_dest_path: >-
      C:\temp\{{ wheel_filename }}
    
  
  tasks:      
    - name: Build package (local)
      delegate_to: localhost
      # We usually inherit a `become: True`, causing Ansible to try to escalate to
      # `root` locally as well, which is not what we want. Need to explicitly tell
      # Ansible not to become.
      become: False
      shell:
        cmd: python setup.py bdist_wheel
        chdir: "{{ CTL_REPO_ROOT }}"
      vars:
        ansible_user: "{{ CTL_USER }}"

    - name: Copy package to target
      win_copy:
        src: "{{ local_src_path }}"
        dest: "{{ remote_dest_path }}"
    
    - name: Stop EPI UE Build Driver service
      ansible.windows.win_service:
        name: EPI UE Build Driver
        state: stopped
      ignore_errors: True

    - name: Un-Install package
      win_shell: >-
        python -m pip uninstall --yes {{ PKG_NAME }}
      # ignore_errors: True
    
    - name: Install package
      win_shell: >-
        python -m pip install {{ remote_dest_path }}
    
    - name: Update server
      win_shell: epi-ue-build-driver update
    
    # - name: Start EPI UE Build Driver service
    #   ansible.windows.win_service:
    #     name: EPI UE Build Driver
    #     state: started

