ansible_connection: winrm
ansible_port: 5986
ansible_winrm_scheme: https
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

ansible_become: True
ansible_become_method: runas

# WIN_GIT_EXT: C:\Program Files\Git\bin\git.exe
